<?php

// Check that is unistall plugin is called
if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) )
    exit();

// Delete all tables and options generated by this plugin avoiding garbage
global $wpdb;
$wpdb->query( "DROP TABLE IF EXISTS wc_bradesco_boleto" );
delete_option("bradesco_boleto_url_dev");
delete_option("bradesco_boleto_url_prod");